### ISSUE TITLE
Cannot retrieve length of file, path = 'null/beauty_1695798917903.jpg' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by SheepYang1993** [MR-MaoJiu/beauty_cam#3]
```
I/libCGE_java( 9812): saving Bitmap : null/beauty_1695798917903.jpg
E/libCGE_java( 9812): Err when saving bitmap...
W/System.err( 9812): java.io.FileNotFoundException: null/beauty_1695798917903.jpg: open failed: ENOENT (No such file or directory)
W/System.err( 9812): 	at libcore.io.IoBridge.open(IoBridge.java:575)
W/System.err( 9812): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W/System.err( 9812): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
W/System.err( 9812): 	at org.wysaid.myUtils.ImageUtil.saveBitmap(ImageUtil.java:30)
W/System.err( 9812): 	at com.example.beauty_cam.CameraFlutterPluginView.lambda$handleCall$0(CameraFlutterPluginView.java:260)
W/System.err( 9812): 	at com.example.beauty_cam.CameraFlutterPluginView$$ExternalSyntheticLambda0.takePictureOK(Unknown Source:4)
W/System.err( 9812): 	at org.wysaid.view.CameraGLSurfaceViewWithTexture$5.run(CameraGLSurfaceViewWithTexture.java:258)
W/System.err( 9812): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1510)
W/System.err( 9812): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)
W/System.err( 9812): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err( 9812): 	at libcore.io.Linux.open(Native Method)
W/System.err( 9812): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/System.err( 9812): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
W/System.err( 9812): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/System.err( 9812): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8141)
W/System.err( 9812): 	at libcore.io.IoBridge.open(IoBridge.java:561)
W/System.err( 9812): 	... 8 more
I/flutter ( 9812): ====================>>>>>>>>null/beauty_1695798917903.jpg
I/mali_config( 9812): @get_buffer_dataspace_setting: update dataspace from GE (0x10010000 -> 0x08020000)

======== Exception caught by image resource service ================================================
The following PathNotFoundException was thrown resolving an image codec:
Cannot retrieve length of file, path = 'null/beauty_1695798917903.jpg' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack: 
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389:7)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1588:31)
<asynchronous suspension>
Path: null/beauty_1695798917903.jpg
====================================================================================================
W/com.example.beauty_cam_example( 9812): type=1400 audit(0.0:1954430): avc: denied { getattr } for comm=474C5468726561642034303936 name="dmabuf:" dev="dmabuf" ino=1 scontext=u:r:untrusted_app:s0:c171,c261,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.example.beauty_cam_example
```

**Comment by SheepYang1993** [comment]
点击拍照的时候报的这个错误。
已经授予存储权限了。

**Comment by MR-MaoJiu** [comment]
你去设置里面看一下是不是真的开启了，如果确认开启了换一个存储位置！有可能你的手机不允许访问这个文件地址

**Comment by MR-MaoJiu** [comment]
null/beauty_1695798917903.jpg
你地址设置的是空的

**Comment by SheepYang1993** [comment]
哦，需要先手动调用一下BeautyCam.setOuPutFilePath(String path)才行哦

**Comment by MR-MaoJiu** [comment]
> 哦，需要先手动调用一下BeautyCam.setOuPutFilePath(String path)才行哦

本来不需要调到我默认给了一个，我不清楚你那边怎么使用的，如果觉得好用可以给个satr哈哈哈哈哈谢谢

**Comment by SheepYang1993** [comment]
我这边就是把项目clone下来，直接运行里面的example项目。然后就会报相机权限、存储权限的错误。

**Comment by SheepYang1993** [comment]
大佬这个项目很棒，就是希望example可以直接跑起来看下效果

**Comment by MR-MaoJiu** [comment]
哈哈哈谢谢，这个本来是可以直接跑起来的，我不太清楚你那边具体问题的原因，看到你的日志是因为保存地址的问题
