### ISSUE TITLE
App crashes when I try to record on Android 13.

### ISSUE THREAD

**Issue by zamargab** [MR-MaoJiu/beauty_cam#7]
I have been building an app with this package for a while now and most times, I run the app on an emulator with Android 7. Everything was working fine until yesterday when I tried to install my app on an emulator running Android 13, to my surprise, the app would crash every time I tried to record a video. Please take a look at the error below.

```
/AndroidRuntime( 4994): FATAL EXCEPTION: main
E/AndroidRuntime( 4994): Process: com.enswag.app, PID: 4994
E/AndroidRuntime( 4994): java.lang.UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found
E/AndroidRuntime( 4994): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime( 4994): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime( 4994): 	at java.lang.System.loadLibrary(System.java:1656)
E/AndroidRuntime( 4994): 	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:9)
E/AndroidRuntime( 4994): 	at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
E/AndroidRuntime( 4994): 	at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
D/Camera  ( 4994): Updating builder with feature: AutoFocusFeature
D/Camera  ( 4994): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 4994): updateNoiseReduction | currentSetting: fast
D/Camera  ( 4994): Updating builder with feature: FocusPointFeature
D/Camera  ( 4994): Updating builder with feature: ResolutionFeature
D/Camera  ( 4994): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 4994): Updating builder with feature: FlashFeature
E/AndroidRuntime( 4994): 	at com.example.beauty_cam.CameraFlutterPluginView.<init>(CameraFlutterPluginView.java:78)
E/AndroidRuntime( 4994): 	at com.example.beauty_cam.CameraFlutterPluginViewFactory.create(CameraFlutterPluginViewFactory.java:28)
E/AndroidRuntime( 4994): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:510)
E/AndroidRuntime( 4994): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
E/AndroidRuntime( 4994): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/AndroidRuntime( 4994): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/AndroidRuntime( 4994): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 4994): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 4994): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 4994): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 4994): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 4994): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4994): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 4994): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 4994): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 4994): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4994): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 4994): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process ( 4994): Sending signal. PID: 4994 SIG: 9

``

**Comment by MR-MaoJiu** [comment]
Alright, I have another issue to fix tomorrow morning. If I can resolve it in the morning, I will work on fixing this problem. But if I don’t have enough time, I will have to postpone it until next month. I’ve been really busy lately. Of course, if you can clone the code and help me identify the possible cause, I might be able to fix it faster. Hahaha!

**Comment by MR-MaoJiu** [comment]
I’m sorry, but currently, I am unable to run the emulator on my end, so I cannot fix this issue temporarily. However, based on your error logs, it seems to be a problem with certain configurations. It is possible that the latest API has modified the way certain configurations are done, resulting in the inability to import certain packages.
